const MedicalGroupList = [
    { 
        name: 'Golden Physicians Medical Group',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Health Excel - XiMED',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Imperial Health Plan of California',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Mercy Physicians Medical Group - MPMG',
        type: 'MG',
        urgentCare: true,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Primary Care Associates of California - PCAC',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Primary Care Associates Medical Group - PCAMG',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
        PCPList : []
    },{ 
        name: 'Regal Medical Group',
        type: 'MG',
        urgentCare: true,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Scripps Clinic Medical',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
    },{ 
        name: 'Scripps Coastal Medical Group',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
    },{ 
        name: 'Scripps Physicians Medical Group - SDPMG',
        type: 'MG',
        urgentCare: true,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Sharp Community Medical Group - SCMG',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'primaryCareProvider',
        taxIDPC: '202138632',
        PCPList : [
            {inGroup: false, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: true, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: true, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: true, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: true, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: true, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{
        name: 'Sharp Rees-Stealy Medical Group',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
    },{ 
        name: 'UCSD - University of California San Diego',
        type: 'MG',
        urgentCare: true,
        urgentCareMessage: 'You will need prior authorization from UCSD for Urgent care visits.',
        inNetwork: true,
        HMOExceptions: ['Anthem Blue Cross (requires prior authorization'],
        flow: 'primaryCareProvider',
        taxIDPC: '832310783',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: false, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'UCSD Monica Perlman Clinic',
        type: 'MG',
        urgentCare: true,
        urgentCareMessage: '',
        inNetwork: true,
        HMOExceptions: [],
        flow: 'allSet',
        taxIDPC: '832310783',
        PCPList : [
            {inGroup: true, onlyCommercial: false, lastName: 'Perlman', firstName: 'Monica'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bhalrhu', firstName: 'Puneet'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Bista', firstName: 'Madalasa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brantz', firstName: 'Edward'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Brunst', firstName: 'Robert'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Buchner', firstName: 'William Jr.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Canelo', firstName: 'Nicholas Peter'},
            {inGroup: true, onlyCommercial: false, lastName: 'Ezzat', firstName: 'Mona'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Kuperman', firstName: 'Ilan'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Macy', firstName: 'Melissa'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Marquis', firstName: 'Paul'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Maxson', firstName: 'Christyanne L.'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Myers', firstName: 'Seymour'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Ortiz', firstName: 'Kenneth'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Parrott', firstName: 'Emilia'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Pitt', firstName: 'William'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Raheem', firstName: 'Mirza'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Soliman', firstName: 'Youstina'}, 
            {inGroup: true, onlyCommercial: false, lastName: 'Stern', firstName: 'Anne E.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Switzer', firstName: 'Jamie L.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Taylor', firstName: 'Susan J.'},
            {inGroup: true, onlyCommercial: false, lastName: 'Tootell', firstName: 'Rhodaline'}
        ],
    },{ 
        name: 'Vantage Medical Group',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
    },{ 
        name: 'Family Health Center of San Diego',
        type: 'MG',
        urgentCare: false,
        urgentCareMessage: '',
        inNetwork: false,
        HMOExceptions: [],
        flow: 'out-of-network',
        taxIDPC: '202138632',
    },
    
];

export default MedicalGroupList;